services:
  server:
    build:
      context: ..
      dockerfile: testproject/server/Dockerfile
      target: dev
    init: true
    command: django-admin runserver 0.0.0.0:8000
    environment:
      DJANGO_SECRET_KEY: secret
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      FRAMEWORK: ${FRAMEWORK}
      VITE_DEVSERVER_URL: ${VITE_DEVSERVER_URL}
      DATABASE_URL: postgres://postgres@postgres/postgres
    ports:
      - 8000:8000
    volumes:
      - ..:/code/
    depends_on:
      postgres:
        condition: service_healthy

  client_react:
    build:
      context: .
      dockerfile: client/react/Dockerfile
      target: dev
    init: true
    command: npm run dev -- --host
    volumes:
      - ..:/code/
    ports:
      - 5173:5173

  client_vue:
    build:
      context: .
      dockerfile: client/vue/Dockerfile
      target: dev
    init: true
    command: npm run dev -- --host
    volumes:
      - ..:/code/
    ports:
      - 5174:5173

  postgres:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
